name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Download H2APK
        run: git clone --depth 1 https://github.com/HashShin/H2APK.git h2apk

      - name: Setup H2APK
        working-directory: h2apk
        run: |
          chmod +x setup.sh
          ./setup.sh

      - name: Build H2APK
        working-directory: h2apk
        run: go build -o h2apk main.go

      - name: Start H2APK
        working-directory: h2apk
        run: |
          ./h2apk &
          sleep 10

      - name: Test H2APK
        run: curl -f http://localhost:8080/
